spring:

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 1000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/next
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

