
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 976760217786-ll08n2e9dkik24tbu1b7sfidq3slurua.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect